services:
  - type: web
    name: flexify-backend
    env: docker
    rootDir: backend
    dockerfilePath: Dockerfile
    branch: main
    autoDeploy: true
    plan: starter

  - type: web
    name: flexify-frontend
    env: docker
    rootDir: frontend
    dockerfilePath: Dockerfile
    branch: main
    autoDeploy: true
    plan: starter